### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'train'

### ISSUE THREAD

**Issue by liu-qi-a** [XueJiang16/NegLabel#2]
I got this error when running dist_train.sh:
`Traceback (most recent call last):
  File "/data/lq/projects/neg_label/tools/train.py", line 203, in <module>
    main()
  File "/data/lq/projects/neg_label/tools/train.py", line 176, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/data/lq/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'train'`
Whether 'clip.py' is the config file of train?
If not , could author share the config file of train.py?Thanks!

**Comment by XueJiang16** [comment]
Hi, the _dist_train.sh_ is the original file in mmclassification and I do not use it. _clip.py_ is generated by myself. So I do not have training config. Maybe you can refer to  https://github.com/open-mmlab/mmpretrain. I hope this can help you.
